CREATE TABLE admission_plan (
    id BIGINT NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    data_version_id BIGINT NOT NULL,
    exam_year INT NOT NULL,
    province_code VARCHAR(32) NOT NULL,
    university_id BIGINT NOT NULL,
    exam_regime VARCHAR(32) NOT NULL,
    plan_type VARCHAR(32) NOT NULL,
    subject_track VARCHAR(32) NULL,
    admission_batch_id BIGINT NOT NULL,
    special_program_type VARCHAR(64) NULL,
    plan_code VARCHAR(128) NOT NULL,
    total_quota INT NULL,
    status VARCHAR(32) NOT NULL,
    source_id BIGINT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_admission_plan_public_id (public_id),
    UNIQUE KEY uk_admission_plan_version_university_code (data_version_id, university_id, plan_code),
    KEY idx_admission_plan_filter (data_version_id, exam_year, plan_type, subject_track, status),
    CONSTRAINT fk_admission_plan_data_version FOREIGN KEY (data_version_id) REFERENCES data_version (id),
    CONSTRAINT fk_admission_plan_university FOREIGN KEY (university_id) REFERENCES university (id),
    CONSTRAINT fk_admission_plan_batch FOREIGN KEY (admission_batch_id) REFERENCES admission_batch (id),
    CONSTRAINT fk_admission_plan_source FOREIGN KEY (source_id) REFERENCES policy_source (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE admission_plan_group (
    id BIGINT NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    admission_plan_id BIGINT NOT NULL,
    group_code VARCHAR(128) NULL,
    group_name VARCHAR(255) NULL,
    group_type VARCHAR(32) NOT NULL,
    first_choice_subject VARCHAR(32) NULL,
    subject_requirement_summary VARCHAR(1000) NULL,
    quota INT NULL,
    status VARCHAR(32) NOT NULL,
    source_id BIGINT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_admission_plan_group_public_id (public_id),
    UNIQUE KEY uk_admission_plan_group_code (admission_plan_id, group_code),
    CONSTRAINT fk_admission_plan_group_plan FOREIGN KEY (admission_plan_id) REFERENCES admission_plan (id),
    CONSTRAINT fk_admission_plan_group_source FOREIGN KEY (source_id) REFERENCES policy_source (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE major_subject_requirement (
    id BIGINT NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    data_version_id BIGINT NOT NULL,
    exam_year INT NOT NULL,
    university_id BIGINT NOT NULL,
    major_id BIGINT NOT NULL,
    requirement_code VARCHAR(128) NOT NULL,
    first_choice_requirement VARCHAR(32) NULL,
    second_choice_mode VARCHAR(32) NOT NULL,
    required_subject_mask VARCHAR(255) NULL,
    requirement_text_raw TEXT NULL,
    status VARCHAR(32) NOT NULL,
    source_id BIGINT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_major_subject_requirement_public_id (public_id),
    UNIQUE KEY uk_major_subject_requirement_code (data_version_id, university_id, major_id, requirement_code),
    CONSTRAINT fk_major_subject_requirement_data_version FOREIGN KEY (data_version_id) REFERENCES data_version (id),
    CONSTRAINT fk_major_subject_requirement_university FOREIGN KEY (university_id) REFERENCES university (id),
    CONSTRAINT fk_major_subject_requirement_major FOREIGN KEY (major_id) REFERENCES major (id),
    CONSTRAINT fk_major_subject_requirement_source FOREIGN KEY (source_id) REFERENCES policy_source (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE admission_plan_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    admission_plan_id BIGINT NOT NULL,
    admission_plan_group_id BIGINT NULL,
    data_version_id BIGINT NOT NULL,
    university_id BIGINT NOT NULL,
    major_id BIGINT NOT NULL,
    external_item_code VARCHAR(128) NOT NULL,
    major_display_name_raw VARCHAR(500) NULL,
    quota INT NULL,
    duration_years INT NULL,
    tuition_amount DECIMAL(12,2) NULL,
    currency_code VARCHAR(3) NULL,
    subject_requirement_id BIGINT NULL,
    adjustment_allowed BOOLEAN NULL,
    notes TEXT NULL,
    status VARCHAR(32) NOT NULL,
    source_id BIGINT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_admission_plan_item_public_id (public_id),
    UNIQUE KEY uk_admission_plan_item_external_code (data_version_id, external_item_code),
    KEY idx_admission_plan_item_data_university (data_version_id, university_id),
    KEY idx_admission_plan_item_plan_group (admission_plan_id, admission_plan_group_id),
    KEY idx_admission_plan_item_major (major_id),
    KEY idx_admission_plan_item_university_major (university_id, major_id),
    KEY idx_admission_plan_item_version_status (data_version_id, status),
    CONSTRAINT fk_admission_plan_item_plan FOREIGN KEY (admission_plan_id) REFERENCES admission_plan (id),
    CONSTRAINT fk_admission_plan_item_group FOREIGN KEY (admission_plan_group_id) REFERENCES admission_plan_group (id),
    CONSTRAINT fk_admission_plan_item_data_version FOREIGN KEY (data_version_id) REFERENCES data_version (id),
    CONSTRAINT fk_admission_plan_item_university FOREIGN KEY (university_id) REFERENCES university (id),
    CONSTRAINT fk_admission_plan_item_major FOREIGN KEY (major_id) REFERENCES major (id),
    CONSTRAINT fk_admission_plan_item_subject_requirement FOREIGN KEY (subject_requirement_id) REFERENCES major_subject_requirement (id),
    CONSTRAINT fk_admission_plan_item_source FOREIGN KEY (source_id) REFERENCES policy_source (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE program_constraint (
    id BIGINT NOT NULL AUTO_INCREMENT,
    admission_plan_item_id BIGINT NOT NULL,
    constraint_type VARCHAR(64) NOT NULL,
    constraint_level VARCHAR(32) NOT NULL,
    constraint_code VARCHAR(128) NOT NULL,
    parameters_json JSON NULL,
    description TEXT NULL,
    policy_source_id BIGINT NULL,
    status VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_program_constraint_item_level (admission_plan_item_id, constraint_level),
    CONSTRAINT fk_program_constraint_item FOREIGN KEY (admission_plan_item_id) REFERENCES admission_plan_item (id),
    CONSTRAINT fk_program_constraint_policy_source FOREIGN KEY (policy_source_id) REFERENCES policy_source (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE control_score_line (
    id BIGINT NOT NULL AUTO_INCREMENT,
    data_version_id BIGINT NOT NULL,
    exam_year INT NOT NULL,
    exam_regime VARCHAR(32) NOT NULL,
    plan_type VARCHAR(32) NOT NULL,
    subject_track VARCHAR(32) NULL,
    admission_batch_id BIGINT NOT NULL,
    special_category VARCHAR(64) NULL,
    score_line DECIMAL(7,2) NOT NULL,
    dimension_hash CHAR(64) NOT NULL,
    source_id BIGINT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_control_score_line_dimension (data_version_id, dimension_hash),
    CONSTRAINT fk_control_score_line_data_version FOREIGN KEY (data_version_id) REFERENCES data_version (id),
    CONSTRAINT fk_control_score_line_batch FOREIGN KEY (admission_batch_id) REFERENCES admission_batch (id),
    CONSTRAINT fk_control_score_line_source FOREIGN KEY (source_id) REFERENCES policy_source (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
