CREATE TABLE admission_history (
    id BIGINT NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    data_version_id BIGINT NOT NULL,
    exam_year INT NOT NULL,
    university_id BIGINT NOT NULL,
    major_id BIGINT NULL,
    plan_type VARCHAR(32) NOT NULL,
    subject_track VARCHAR(32) NULL,
    admission_batch_id BIGINT NOT NULL,
    exam_regime VARCHAR(32) NOT NULL,
    history_grain VARCHAR(32) NOT NULL,
    quota INT NULL,
    lowest_score DECIMAL(7,2) NULL,
    lowest_rank BIGINT NULL,
    average_score DECIMAL(7,2) NULL,
    average_rank BIGINT NULL,
    highest_score DECIMAL(7,2) NULL,
    highest_rank BIGINT NULL,
    control_score_line DECIMAL(7,2) NULL,
    dimension_hash CHAR(64) NOT NULL,
    quality_status VARCHAR(32) NOT NULL,
    source_id BIGINT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_admission_history_public_id (public_id),
    UNIQUE KEY uk_admission_history_dimension (data_version_id, dimension_hash),
    KEY idx_admission_history_university (exam_year, university_id, plan_type, subject_track),
    KEY idx_admission_history_major (major_id, exam_year),
    KEY idx_admission_history_lowest_rank (lowest_rank),
    CONSTRAINT fk_admission_history_data_version FOREIGN KEY (data_version_id) REFERENCES data_version (id),
    CONSTRAINT fk_admission_history_university FOREIGN KEY (university_id) REFERENCES university (id),
    CONSTRAINT fk_admission_history_major FOREIGN KEY (major_id) REFERENCES major (id),
    CONSTRAINT fk_admission_history_batch FOREIGN KEY (admission_batch_id) REFERENCES admission_batch (id),
    CONSTRAINT fk_admission_history_source FOREIGN KEY (source_id) REFERENCES policy_source (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
