CREATE TABLE recommendation_request (
    id BIGINT NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    exam_profile_id BIGINT NOT NULL,
    eligibility_profile_id BIGINT NOT NULL,
    preference_profile_id BIGINT NOT NULL,
    request_hash CHAR(64) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    locale VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_recommendation_request_public_id (public_id),
    UNIQUE KEY uk_recommendation_request_idempotency (user_id, idempotency_key),
    KEY idx_recommendation_request_candidate_created (candidate_id, created_at),
    CONSTRAINT fk_recommendation_request_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_recommendation_request_candidate FOREIGN KEY (candidate_id) REFERENCES candidate (id),
    CONSTRAINT fk_recommendation_request_exam_profile FOREIGN KEY (exam_profile_id) REFERENCES candidate_exam_profile (id),
    CONSTRAINT fk_recommendation_request_eligibility_profile FOREIGN KEY (eligibility_profile_id) REFERENCES candidate_eligibility_profile (id),
    CONSTRAINT fk_recommendation_request_preference_profile FOREIGN KEY (preference_profile_id) REFERENCES candidate_preference_profile (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE recommendation_run (
    id BIGINT NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    recommendation_request_id BIGINT NOT NULL,
    rule_set_id BIGINT NOT NULL,
    admission_plan_data_version_id BIGINT NOT NULL,
    admission_history_data_version_id BIGINT NOT NULL,
    control_line_data_version_id BIGINT NOT NULL,
    algorithm_version VARCHAR(64) NOT NULL,
    run_status VARCHAR(32) NOT NULL,
    audit_level VARCHAR(32) NOT NULL,
    candidate_pool_count INT NULL,
    hard_filtered_count INT NULL,
    final_result_count INT NULL,
    started_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    error_code VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_recommendation_run_public_id (public_id),
    KEY idx_recommendation_run_request_created (recommendation_request_id, created_at),
    KEY idx_recommendation_run_status_created (run_status, created_at),
    CONSTRAINT fk_recommendation_run_request FOREIGN KEY (recommendation_request_id) REFERENCES recommendation_request (id),
    CONSTRAINT fk_recommendation_run_rule_set FOREIGN KEY (rule_set_id) REFERENCES rule_set (id),
    CONSTRAINT fk_recommendation_run_plan_data_version FOREIGN KEY (admission_plan_data_version_id) REFERENCES data_version (id),
    CONSTRAINT fk_recommendation_run_history_data_version FOREIGN KEY (admission_history_data_version_id) REFERENCES data_version (id),
    CONSTRAINT fk_recommendation_run_control_line_data_version FOREIGN KEY (control_line_data_version_id) REFERENCES data_version (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE recommendation_result_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    recommendation_run_id BIGINT NOT NULL,
    admission_plan_item_id BIGINT NOT NULL,
    recommendation_tier VARCHAR(32) NOT NULL,
    risk_level VARCHAR(32) NOT NULL,
    risk_score DECIMAL(7,2) NULL,
    preference_score DECIMAL(7,2) NULL,
    overall_score DECIMAL(7,2) NULL,
    comparability_score DECIMAL(7,2) NULL,
    rank_order INT NOT NULL,
    is_visible_free BOOLEAN NOT NULL DEFAULT FALSE,
    reason_summary TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_recommendation_result_item_public_id (public_id),
    UNIQUE KEY uk_recommendation_result_item_rank (recommendation_run_id, rank_order),
    KEY idx_recommendation_result_item_tier_rank (recommendation_run_id, recommendation_tier, rank_order),
    CONSTRAINT fk_recommendation_result_item_run FOREIGN KEY (recommendation_run_id) REFERENCES recommendation_run (id),
    CONSTRAINT fk_recommendation_result_item_plan_item FOREIGN KEY (admission_plan_item_id) REFERENCES admission_plan_item (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE recommendation_rule_trace (
    id BIGINT NOT NULL AUTO_INCREMENT,
    recommendation_run_id BIGINT NOT NULL,
    recommendation_result_item_id BIGINT NULL,
    rule_id BIGINT NULL,
    rule_code VARCHAR(128) NOT NULL,
    trace_scope VARCHAR(32) NOT NULL,
    result_type VARCHAR(32) NOT NULL,
    reason_code VARCHAR(128) NULL,
    input_summary_json JSON NULL,
    output_summary_json JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_recommendation_rule_trace_run (recommendation_run_id, trace_scope),
    CONSTRAINT fk_recommendation_rule_trace_run FOREIGN KEY (recommendation_run_id) REFERENCES recommendation_run (id),
    CONSTRAINT fk_recommendation_rule_trace_result_item FOREIGN KEY (recommendation_result_item_id) REFERENCES recommendation_result_item (id),
    CONSTRAINT fk_recommendation_rule_trace_rule FOREIGN KEY (rule_id) REFERENCES business_rule (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE recommendation_run_snapshot (
    id BIGINT NOT NULL AUTO_INCREMENT,
    recommendation_run_id BIGINT NOT NULL,
    snapshot_type VARCHAR(32) NOT NULL,
    snapshot_json JSON NOT NULL,
    sha256 CHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_recommendation_run_snapshot (recommendation_run_id, snapshot_type),
    CONSTRAINT fk_recommendation_run_snapshot_run FOREIGN KEY (recommendation_run_id) REFERENCES recommendation_run (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
